# -*- coding: utf-8 -*-
"""shapeAI network project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sO8jk7Nyomv9U-FPwQeNv78EqEIoEjJK
"""

import hashlib

result = hashlib.md5(b'md5 hash generation')
print(result.digest())

import hashlib
str = "Python Hash Functions"
md5result=hashlib.md5(str.encode())
print("md5 hash :",md5result.hexdigest())

sha256result=hashlib.sha256(str.encode())
print("sha256 hash :",sha256result.hexdigest())

sha1result=hashlib.sha1(b'sha1 hashing')
print("sha1 hash :",sha1result.digest())

import hashlib, uuid

password = "sample_password"
salt = uuid.uuid4().hex
hashed_password = hashlib.sha512((password + salt).encode())
print("Salt Hash :", hashed_password.hexdigest())

for x in range(6):
     hashed_password = hashlib.sha512((salt + hashed_password.hexdigest()).encode())

print("Salt & Iteration Hash :", hashed_password.hexdigest())